"""add_is_pinned_to_content

Revision ID: f9bbc875c702
Revises: 6c1f9c7b4e2a
Create Date: 2026-02-13 12:55:28.148075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9bbc875c702"
down_revision: Union[str, None] = "6c1f9c7b4e2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "content",
        sa.Column("is_pinned", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index(
        op.f("ix_content_is_pinned"), "content", ["is_pinned"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_content_is_pinned"), table_name="content")
    op.drop_column("content", "is_pinned")
    # ### end Alembic commands ###
